export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const OPEN_CONFIRMATION_DIALOG = 'OPEN_CONFIRMATION_DIALOG';
export const CLOSE_CONFIRMATION_DIALOG = 'CLOSE_CONFIRMATION_DIALOG';

export const OPEN_EDIT_CARD_DIALOG = 'OPEN_EDIT_CARD_DIALOG';
export const CLOSE_EDIT_CARD_DIALOG = 'CLOSE_EDIT_CARD_DIALOG';

export const OPEN_SUCCESS_DIALOG = 'OPEN_SUCCESS_DIALOG';
export const CLOSE_SUCCESS_DIALOG = 'CLOSE_SUCCESS_DIALOG';
