// Auth 
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

// Dialogs
export const OPEN_CONFIRMATION_DIALOG = 'OPEN_CONFIRMATION_DIALOG';
export const CLOSE_CONFIRMATION_DIALOG = 'CLOSE_CONFIRMATION_DIALOG';

export const OPEN_EDIT_CARD_DIALOG = 'OPEN_EDIT_CARD_DIALOG';
export const CLOSE_EDIT_CARD_DIALOG = 'CLOSE_EDIT_CARD_DIALOG';

export const OPEN_SUCCESS_DIALOG = 'OPEN_SUCCESS_DIALOG';
export const CLOSE_SUCCESS_DIALOG = 'CLOSE_SUCCESS_DIALOG';

// Generic
export const FETCH_ALL = 'FECTCH_ALL';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const FETCH_ONE = 'FETCH_ONE';
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const OPEN_FORM = 'OPEN_FORM';
export const CLOSE_FORM = 'CLOSE_FORM';

// Users page actions 

export const OPEN_USER_FORM_DIALOG = 'OPEN_USER_FORM_DIALOG';
export const CLOSE_USER_FORM_DIALOG = 'CLOSE_USER_FORM_DIALOG';
export const FETCH_USERS = 'FETCH_USERS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const START_LOADING_USER = 'START_LOADING_USER';

export const SEND_REQUEST = 'SEND_REQUEST'
export const FAILED_USER_REQUEST = 'FAILED_USER_REQUEST'
export const SET_USER = 'SET_USER';

// Risks page actions 

export const FETCH_RISKS = 'FETCH_RISKS';
export const SEARCH_RISKS = 'SEARCH_RISKS';
export const FETCH_RISK = 'FETCH_RISK';
export const CREATE_RISK = 'CREATE_RISK';
export const UPDATE_RISK = 'UPDATE_RISK';
export const START_LOADING_RISK = 'START_LOADING_RISK';
export const END_LOADING_RISK = 'END_LOADING_RISK';
export const OPEN_RISK_FORM_DIALOG = 'OPEN_RISK_FORM_DIALOG';
export const CLOSE_RISK_FORM_DIALOG = 'CLOSE_RISK_FORM_DIALOG';
export const FAILED_RISK_REQUEST = 'FAILED_RISK_REQUEST'
export const SET_RISK = 'SET_RISK';
export const FETCH_RISKS_IMPACTS = 'FETCH_RISKS_IMPACTS';

